check out deploy

diff --git a/.github/workflows/deploy-app.yaml b/.github/workflows/deploy-app.yaml
--- a/.github/workflows/deploy-app.yaml
+++ b/.github/workflows/deploy-app.yaml
@@ -55,42 +55,54 @@ jobs:
       - name: Build code server
         run: npm run build
 
-  deploy-server:
-    runs-on: ubuntu-latest
-    needs: build-code-server
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # deploy-server:
+  #   runs-on: ubuntu-latest
+  #   needs: build-code-server
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up SSH
-        uses: webfactory/ssh-agent@v0.5.4
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+  #     - name: Set up SSH
+  #       uses: webfactory/ssh-agent@v0.5.4
+  #       with:
+  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      - name: Add server to known hosts
-        run: |
-          mkdir -p ~/.ssh
-          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
+  #     - name: Add server to known hosts
+  #       run: |
+  #         mkdir -p ~/.ssh
+  #         ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
 
-      - name: Deploy to server
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
-            cd /path/to/your/app || exit
-            git pull origin main
-            npm install
-            npm run build
-            pm2 restart all
-          EOF
+  #     - name: Deploy to server
+  #       run: |
+  #         ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
+  #           cd /path/to/your/app || exit
+  #           git pull origin main
+  #           npm install
+  #           npm run build
+  #           pm2 restart all
+  #         EOF
 
-      - name: Notify deployment success
-        run: echo "Deployment to server completed successfully!"
+  #     - name: Notify deployment success
+  #       run: echo "Deployment to server completed successfully!"
 
-      - name: Notify deployment failure
-        if: failure()
-        run: echo "Deployment to server failed!"
+  #     - name: Notify deployment failure
+  #       if: failure()
+  #       run: echo "Deployment to server failed!"
 
-      - name: Clean up
-        run: rm -rf ~/.ssh/known_hosts
+  #     - name: Clean up
+  #       run: rm -rf ~/.ssh/known_hosts
 
-      - name: End of workflow
-        run: echo "Workflow completed."
+  #     - name: End of workflow
+  #       run: echo "Workflow completed."
+deploy-vercel:
+  runs-on: ubuntu-latest
+  needs: build-code-server
+  steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Install Vercel CLI
+      run: npm install -g vercel
+
+    - name: Deploy to Vercel
+      run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
